### ISSUE TITLE
Playback not working

### ISSUE THREAD

**Issue by gamemasta0** [gillesdemey/Cumulus#100]
It appears as if Cumulus can't access the track to begin playing. I click play on any track and it begins skipping through the entire list, making the previous songs' text crossed through as if it thinks the track doesn't exist. Is there a log I can capture to help resolve this?

I'm running macOS Sierra 10.12.5

**Comment by MichielDeMey** [comment]
Hi, looks like you are running into https://github.com/gillesdemey/Cumulus/issues/89, let us know if it's not related.

**Comment by gamemasta0** [comment]
Looks like you're right! Thanks for taking a look at this!
