### ISSUE TITLE
Add issue template to tell people about #89

### ISSUE THREAD

**Issue by seppestas** [gillesdemey/Cumulus#102]
A lot of issues get created that are duplicates of #89. We should consider creating an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) telling people about the rate limiting issues that links to #89.

**Comment by Hum4n01d** [comment]
I agree 👍

**Comment by seppestas** [comment]
Fixed in 58aaa9289b0e59f35d36a7841483a49e48a7b367
