### ISSUE TITLE
Very weird behavior no playback

### ISSUE THREAD

**Issue by sittingbool** [gillesdemey/Cumulus#104]
<img width="328" alt="bildschirmfoto 2017-07-14 um 13 52 31" src="https://user-images.githubusercontent.com/12949701/28211216-c5f0f34a-689b-11e7-8d3c-57c62f7233c4.png">
Started Cumulus -> Sign in -> Go to Feed / Likes / Playlists -> Click Play 

-> it shows covers changing a lot and the text gets striked through then it does taht for a while but even if i hit play nothing works

**Comment by MichielDeMey** [comment]
This is a rate limit issue, see https://github.com/gillesdemey/Cumulus/issues/89
