### ISSUE TITLE
Facebook login need cookie enabled

### ISSUE THREAD

**Issue by adzymaniac** [gillesdemey/Cumulus#15]
Thanks for this great work. Anyway, we have small problem with facebook login.

![screen shot 2015-09-15 at 12 18 50 pm](https://cloud.githubusercontent.com/assets/629402/9868621/6db5863c-5ba5-11e5-8e46-802f12762b8d.png)

**Comment by MichielDeMey** [comment]
I've seen this happening before on Windows as well,
cookies are not required for authentication to work though.

Can you login without checking the "remember me" checkbox?

**Comment by adzymaniac** [comment]
The "remember me" was not checked. Still same warning

**Comment by killa-kyle** [comment]
I have the same issue. 'remember me' is not checked

**Comment by aratno** [comment]
Same here

**Comment by chryton** [comment]
Same issue. I tried it both checked and unchecked.

**Comment by MichielDeMey** [comment]
Hey guys, we just released v0.5.1 which should take care of this issue!
https://github.com/gillesdemey/Cumulus/releases/tag/v0.5.1

**Comment by 3rd-Eden** [comment]
Just tried the latest version, 8.0 and it's having these issues as well.

**Comment by chrisjansky** [comment]
Still happening for me on macOS 10.11 and Cumulus 0.10.0.

**Comment by DarrylD** [comment]
Still happening. Any solution for this?

**Comment by allyouaskfor** [comment]
macOS 10.12.3 still having this issue.

**Comment by gillesdemey** [comment]
Hey folks, can you please retry with the latest 0.10.1 release and get back to me?
