### ISSUE TITLE
Quit button does nothing

### ISSUE THREAD

**Issue by CapitanRedBeard** [gillesdemey/Cumulus#17]
I noticed that the quit button is not doing anything on my OSX Yosemite 10.10.3. Love the app btw

**Comment by MichielDeMey** [comment]
We're unable to reproduce this issue using the following:

Cumulus 0.4.0
OSX: 10.11
Closing the app using the quit button in the "radar" menu

Which version of Cumulus were you using?

**Comment by CapitanRedBeard** [comment]
Was using 0.4.0, but after a computer restart it looks like the issue was just me! Closing the issue~
