### ISSUE TITLE
Media button prio.

### ISSUE THREAD

**Issue by maertz** [gillesdemey/Cumulus#19]
I would appreciate if the media buttons would not cancel the other programs, means if i open / focus itunes the media buttons does not work anymore. If you take spotify in comparision it works just like i would expect from this app. Would be a nice to have.

**Comment by gillesdemey** [comment]
Unfortunately this is how Electron's global shortcuts work, I've been annoyed by this as well but the reality is that Cumulus doesn't control this behaviour.
