### ISSUE TITLE
window position is off when using external monitor

### ISSUE THREAD

**Issue by cbrumelle** [gillesdemey/Cumulus#22]
If I plug my laptop (running OSX 10.9.5) into an external monitor, the position of the player window is not correct, and it appears in the middle of the display (looks like it might be in the same absolute position that it would appear on the laptop display?). See screenshot of the external monitor display:
<img width="1281" alt="image 2015-10-20 at 12 54 53 pm" src="https://cloud.githubusercontent.com/assets/164823/10619331/f2a77d9c-7729-11e5-8894-d961819242a4.png">

Position is correct on the laptop though and I'm loving the app. Thanks!

**Comment by Bitbored** [comment]
Yeah, I think this is an issue with [menubar](https://github.com/maxogden/menubar). I started working on fixing this some time ago, but because of some merge conflict I haven't gotten around to pushing it...

**Comment by cbrumelle** [comment]
Interestingly, if I build from source as opposed to downloading the prebuilt, it works fine so ... ¯\_(ツ)_/¯

**Comment by gillesdemey** [comment]
Hey @cbrumelle has this been resolved with any of the latest releases? I don't currently have access to a second monitor to give it a try.

If it still occurs, I think @Bitbored can take a look at this.

**Comment by cbrumelle** [comment]
Latest release seems good!
