### ISSUE TITLE
Can't cancel/go back after choosing Facebook signin

### ISSUE THREAD

**Issue by chrismessina** [gillesdemey/Cumulus#26]
When I choose Facebook login but then changed my mind, the Cancel button didn't bring me back to the SoundCloud login page.

**Comment by chryton** [comment]
This is also blocking quitting the application to reset the login problem from #15.

**Comment by MichielDeMey** [comment]
Hey guys, both issues should be fixed now. :)
https://github.com/gillesdemey/Cumulus/releases/tag/v0.5.2
