### ISSUE TITLE
Playlists stuck on loading animation when you have no playlists

### ISSUE THREAD

**Issue by kokarn** [gillesdemey/Cumulus#3]
After debugging for a while with help from #2, i realised that i might not have any playlists and that's why it's stuck on the loading animation.

Turns out that was the problem all along. 
Maybe just display a text that you have no playlists or something instead?

Thanks for a great app <3

**Comment by gillesdemey** [comment]
This is fixed, you can download the latest version at the URL defined in the README.

**Comment by kokarn** [comment]
Thanks, great work!
