### ISSUE TITLE
High memory usage 

### ISSUE THREAD

**Issue by sammcj** [gillesdemey/Cumulus#31]
For such a simple / small application Cumulus' memory usage is very high.

A fresh install and launch easily uses 130MB which is considerably more than many more complex applications (iStats, LittleSnitch, Reeder, Dropbox, iTerm and even mail!).

<img width="280" alt="screen shot 2015-10-31 at 1 15 56 pm" src="https://cloud.githubusercontent.com/assets/862951/10861396/9f416acc-7fd1-11e5-8c05-ab5b354b5d26.png">

**Comment by MichielDeMey** [comment]
Yup, this is because it's not entirely a native application.
(Cross platform support for Cumulus is underway!)

We're using Electron, built by GitHub, which has an embedded WebKit we use to render our application.
