### ISSUE TITLE
Signing-in with Google does not work

### ISSUE THREAD

**Issue by mahmoudajawad** [gillesdemey/Cumulus#34]
Hello,,

My Soundcloud account is associated with a Google account, i've never had a standalone Soundcloud account. When i tried to start Cumulus i was prompted with the authorization window, where i chose "Sign-in with Google", it opened a new window with Google Accounts interface asking me for my credentials, after inputting that the page started to reload with the window title changing to "Connecting..." with a blank page. i guess the app is not able to handle the fallback response from the google accounts interface or something like that.

**Comment by Bitbored** [comment]
What happens when you restart the app? Does it ask for authentication again, or does it fail to start with a blank page?

**Comment by gillesdemey** [comment]
It's possible that Google uses a different query string parameter, I'll take a look at it.

**Comment by AjawadMahmoud** [comment]
@Bitbored, it does show the same Soundcloud authorization window again, however, if i click on "Sign-in with Google" it opens a new window with the title "Connecting..." which means it's still having my Google Account authorization info there, but the redirecting part is not happening. can someone check if it's reproducable on other platforms and other devices?

**Comment by ghs21** [comment]
STOP SENDING E-MAILS TO THIS GUY GILLES DEMEY/CUMULUS : ALL YOUR MAILS ARE
COMING IN MY GMAIL INBOX dotidam@gmail.com
HOPE NO RECALL WIIL BE NEEDED


2015-11-03 4:49 GMT+01:00 Mahmoud Abdul Jawad <notifications@github.com>:

**Comment by gillesdemey** [comment]
Hello ghs21,

It appears that you have watched the Cumulus repo. 

You can stop receiving these emails by clicking “unwatch” on the project’s page here https://github.com/gillesdemey/Cumulus/watchers.

Kind regards,

Gilles

**Comment by ghs21** [comment]
Georges Strickaert
dotidam@gmail.com

**Comment by AjawadMahmoud** [comment]
@ghs21, dude! @gillesdemey instructions were clear; login to GitHub, go to this https://github.com/gillesdemey/Cumulus and then from the top right "watch" menu choose "Not Watching". After that, choose to "Unsubscribe" to this issue by opening https://github.com/gillesdemey/Cumulus/issues/34 and choose "Unsubscribe" from the right menu.

**Comment by Bitbored** [comment]
@ghs21, see this: https://help.github.com/articles/unsubscribing-from-conversations/

**Comment by Bitbored** [comment]
Oh crapp, we should also stop mentioning him apparently... My fault.

**Comment by MichielDeMey** [comment]
We believe that Google does not support non http oauth callbacks.
Since we're using an application specific protocol (cumulus://) this might be difficult to solve without setting up an external backend for Cumulus to handle oauth callbacks.

The latter is not immediately on our to-do list. :)

**Comment by AjawadMahmoud** [comment]
Alright, I suppose I need to work on it myself then. Maybe.
Let me see what I can do when I get time.

**Comment by JokerQyou** [comment]
I have a different error when I try to login with Google account, as this screenshot.
![image](https://cloud.githubusercontent.com/assets/1465267/15919619/abaa0c24-2e45-11e6-983d-4d91ad78b382.png)

**Comment by mahmoudajawad** [comment]
Closing this as I'm no longer attending this issue.
