### ISSUE TITLE
Media buttons trigger other players

### ISSUE THREAD

**Issue by jaflo** [gillesdemey/Cumulus#35]
Media buttons control both Cumulus and other players. To replicate open Cumulus and another application (such as VLC). Then try using the keyboard buttons. Both applications respond.

**Comment by gillesdemey** [comment]
I can't get them to respond both, VLC does however swallow the media key events. I'll look into this but this is very likely a duplicate of https://github.com/gillesdemey/Cumulus/issues/19.

**Comment by gillesdemey** [comment]
Duplicate of #19
