### ISSUE TITLE
Cumuls failed to retrieve feed

### ISSUE THREAD

**Issue by quentinlesceller** [gillesdemey/Cumulus#37]
When started, Cumulus try to retrieve the music from the fed tab but the app never stop loading (See screenshot 1).
![screenshot 1](https://cloud.githubusercontent.com/assets/11842328/11543572/79624c6a-990b-11e5-9cb3-8cdc1db3676d.png)
When I click on the "Like" tab, the music are retrieved. Then, when I click on the "Feed" tab, I have the message "sorry something went wrong" (see figure 2).
![screenshot 2](https://cloud.githubusercontent.com/assets/11842328/11543627/ba53d806-990b-11e5-969c-9ad4b043b03a.png)
This problem appeared approximately one week ago. I tried to get the latest version and compiled it again but the problem remains.

Mac OS X 10.11.1

Thank you

**Comment by kokarn** [comment]
I think this is a dupe of #14, or at least related

**Comment by gillesdemey** [comment]
This might indeed be a duplicate as @kokarn mentioned.

That being said, I've released a new version that takes care of a particular edge-case that might solve this issue.

https://github.com/gillesdemey/Cumulus/releases/tag/v0.5.4

**Comment by quentinlesceller** [comment]
Issue solved ! Thank you !
