### ISSUE TITLE
Include Liked Playlists in LIKES or PLAYLISTS Tab

### ISSUE THREAD

**Issue by mutewinter** [gillesdemey/Cumulus#38]
Soundcloud puts them in the Playlists area, which seems fine.

![screen shot 2015-12-10 at 10 31 59 am](https://cloud.githubusercontent.com/assets/305901/11721412/49cf7d0a-9f29-11e5-9f44-91ddede49eea.png)

**Comment by jpknegtel** [comment]
Second this!

**Comment by gillesdemey** [comment]
I hear you, I wanted this to be part of the initial release too. 

Sadly, SoundCloud's API does not support "liked" playlists. SoundCloud's v2 API does however support these operations but aren't considered "stable" yet. 

I'm working on a client for their latest API but haven't gotten around to reviewing it and implementing it. 
https://github.com/gillesdemey/soundcloud-v2

**Comment by Mc01** [comment]
After testing #50 this issue can be closed? :)

**Comment by gillesdemey** [comment]
I've released this as version 0.6.0, with a PR from @Mc01.
