### ISSUE TITLE
Make artist & track clickable in "now playing"

### ISSUE THREAD

**Issue by kokarn** [gillesdemey/Cumulus#4]
If you play from your feed and find a nice track there is no easy way to go to or like it.

**Comment by gillesdemey** [comment]
Can you elaborate on the way you'd see this work?

Clicking the artist or track title should take you to the website?

And you can like a track simply by clicking the "heart" icon in the media player.

**Comment by gillesdemey** [comment]
Resolved in v0.3.3

**Comment by kokarn** [comment]
Oh sorry, missed your last post.
Sorry about missing the heart, and thanks for the 0.3.3 <3
