### ISSUE TITLE
Playlist, feed and likes pages not getting loaded

### ISSUE THREAD

**Issue by ravjot28** [gillesdemey/Cumulus#42]
When i successfully log in and try to access Playlist, feed and likes pages i see weird orange circular animation it is weird coz i can only see right top part of the circle only rest is invisible and after some time i get a message Sorry, something went wrong.

PFA the screenshots
<img width="316" alt="screen shot 2016-01-01 at 1 18 00 pm" src="https://cloud.githubusercontent.com/assets/5196834/12071753/28979f38-b08a-11e5-832f-a46b3e8c0e23.png">
<img width="310" alt="screen shot 2016-01-01 at 1 18 15 pm" src="https://cloud.githubusercontent.com/assets/5196834/12071754/28a706bc-b08a-11e5-86fc-5ad44c2b7ce8.png">

**Comment by gillesdemey** [comment]
What version of Cumulus are you using?

**Comment by ravjot28** [comment]
0.5.4

**Comment by chloesil** [comment]
I am also having this problem, on the same version.

**Comment by MichielDeMey** [comment]
If you're up to the task, you can try and replicate the issue using a development build.
That way you have access to the dev console and are able to check the stack trace. :)

**Comment by chloesil** [comment]
@MichielDeMey I would love to help but honestly I don't know how to do what you're suggesting!

**Comment by rnarian** [comment]
I just installed the app and ran into a similar problem. Everything seems to work fine until I open the playlists tab. After that all tabs show the "sorry something went wrong" error message:

![untitled](https://cloud.githubusercontent.com/assets/1174951/13283855/95762788-daf0-11e5-8fd4-1fc69d5a0154.gif)

**Comment by rnarian** [comment]
I just built the app from source, but I am experiencing the same behavior. Unfortunately no errors are showing up:

![untitled](https://cloud.githubusercontent.com/assets/1174951/13284982/2bbc4388-daf8-11e5-938b-8abab1f627f8.gif)

**Comment by Mc01** [comment]
@rnarian I believe you can try this with new version (>=0.5.7), which has debugger inside main window.
#48

**Comment by Mc01** [comment]
I'm guessing that I had today this issue.
In my case it was connected with: http://stackoverflow.com/questions/33485387/soundcloud-api-returning-0-tracks-despite-user-having-tracks
Here's the screenshot with errors. (it broke on empty playlist)
<img width="926" alt="screen shot 2016-03-03 at 15 52 58" src="https://cloud.githubusercontent.com/assets/2324400/13498182/3b7a3048-e159-11e5-8156-58a61cea1a7d.png">

**Comment by Mc01** [comment]
If you want to replicate issue. Save this track as a new playlist: https://soundcloud.com/dewprocess/last-dinosaurs-zoom
