### ISSUE TITLE
Use doorhanger (arrow) UI for native look and feel

### ISSUE THREAD

**Issue by bogas04** [gillesdemey/Cumulus#43]
Usually menu bar apps use a door hanger in OSX, which is also used at several places in the OS itself.
It can be implemented as explained in https://github.com/maxogden/menubar/issues/100#issuecomment-168311340

![Example Screenshot](https://cloud.githubusercontent.com/assets/6177621/12066986/be8e7cdc-b017-11e5-96cb-73ad01a6bb65.png)

**Comment by gillesdemey** [comment]
I've tried this before, but that means sacrificing the native shadow placed on the window. Unfortunately you can't add a shadow back in using something like `box-shadow`, so I've decided to go without a door hanger for the initial release.

**Comment by gillesdemey** [comment]
I'm closing this one as there is currently no way to have a doorhanger combined with the shadow drop using Electron.
