### ISSUE TITLE
Show Cumulus window at current sound when clicking OSX notification

### ISSUE THREAD

**Issue by andersfischernielsen** [gillesdemey/Cumulus#44]
It'd be awesome if the Cumulus window would appear displaying the current sound playing when the user clicks the "sound changed" OS notification (I don't know if Windows shows a similar notification).

![screen shot 2016-01-21 at 10 26 04](https://cloud.githubusercontent.com/assets/5990738/12476440/9739a5d6-c029-11e5-8adf-e25442ab5de6.png)

The feature could, as far as I can see, be implemented by displaying the Cumulus window as-is, since the currently playing sound is already in focus there.

**Comment by andersfischernielsen** [comment]
It seems like the app uses default Electron notifications.

    //Found in "currentTrackStore.js"
    
    function _showNotification(track) {
      if (document.visibilityState !== 'hidden') return
      new window.Notification(track.user.username, {
        body : track.title,
        icon : track.artwork_url,
      })
    }

OnClick-events are supported by using: 

    var myNotification = new Notification('Title', {
      body: 'Lorem Ipsum Dolor Sit Amet'
    });

    myNotification.onclick = function () {
      console.log('Notification clicked')
    }

    https://github.com/atom/electron/blob/master/docs/tutorial/desktop-environment-integration.md#notifications-windows-linux-os-x

**Comment by rnarian** [comment]
The problem remains if you skip a few tracks (via the media keys) and open up the app again. Wouldn't it make more sense if the app automatically scrolls to the current playing track whenever I focus the app window. This should solve @andersfischernielsen&#65279;s issue as well?
