### ISSUE TITLE
Cumulus "steals" play/pause buttons on MacBooks

### ISSUE THREAD

**Issue by andersfischernielsen** [gillesdemey/Cumulus#45]
The keyboard play/skip/pause buttons on Macs are "stolen" from other apps supporting these when Cumulus is running. 

If iTunes/Spotify is running, has been playing sound most recently, and Cumulus is open, the play/pause/skip buttons should control iTunes/Spotify (regular system behaviour). They do not, though. Cumulus is always reacting to the button presses, and iTunes/Spotify does not.

**Comment by jdsimcoe** [comment]
Personally, I like that they "steal" the default play/pause buttons. I think this is one of its selling features.

**Comment by andersfischernielsen** [comment]
The default system behaviour is that the most recently used app reacts to the play/pause/skip buttons. 

Say you have Spotify and iTunes open, and you've used Spotify most recently. Then iTunes won't start playing if Spotify is active/in focus. 

IMO Cumulus should do the same, since it's system behaviour.

**Comment by gillesdemey** [comment]
Cumulus cannot change the behaviour of how the global key listeners are set up (see #19), if you think that this is still an issue please file one with Electron :)

**Comment by andersfischernielsen** [comment]
Cool, thanks for addressing this. :)
