### ISSUE TITLE
Debug window in development mode is not responding

### ISSUE THREAD

**Issue by Mc01** [gillesdemey/Cumulus#47]
After starting Cumulus in development mode I cannot interact with debug window.
It looks like it has been drawn once on my wallpaper and I cannot interact with it.
At screenshot you can see icons and cursor selection on my desktop over it.

<img width="1280" alt="screen shot 2016-02-24 at 22 29 14" src="https://cloud.githubusercontent.com/assets/2324400/13301652/49f803fc-db46-11e5-9710-2d62d8f48a6b.png">

**Comment by gillesdemey** [comment]
Fixed in #48
