### ISSUE TITLE
Cumulus does not react to headphone controls

### ISSUE THREAD

**Issue by andersfischernielsen** [gillesdemey/Cumulus#49]
On OSX El Capitan Cumulus does not pause/play when a clicker on a pair of headphones is used for controlling the music.

**Comment by gillesdemey** [comment]
Do the headphone clickers work with iTunes? Cumulus (Electron) is just hooking into the global Play / Pause events and reacting to those.

**Comment by andersfischernielsen** [comment]
Yeah, the headphone clickers work perfectly with iTunes and Quicktime (though not Spotify).

**Comment by vjanssens** [comment]
To be clear, I think Anders means the middle button on the [Apple EarPods](http://www.apple.com/nl/shop/product/MD827ZM/B/apple-earpods-met-afstandsbediening-en-microfoon). I can confirm this button does not 'pause' the music when pressed once. Using OSX El Capitan + latest version of Cumulus.

Next, previous, pause/play buttons on my keyboard work as expected.

**Comment by andersfischernielsen** [comment]
Exactly. :)

**Comment by MichielDeMey** [comment]
I can confirm this issue.
Volume buttons on the side work as expected, but the middle button seems to open iTunes.

We're going to look into this to see if we can capture the middle button, but don't get your hopes up. :)

**Comment by jneubrand** [comment]
Recently came across this: https://github.com/wmttom/MikeyPlay – clearly, it's _possible_, but I'm not sure how this should be handled in Cumulus. Maybe we can ask the electron team to implement headphone button capturing?

**Comment by bendingtime** [comment]
Nothing is needed just install [spotify bluetooth headset listener](https://github.com/jguice/mac-bt-headset-fix) and it will work perfectly.

**Comment by seppestas** [comment]
I personally use [BTHSControl](https://github.com/JamesFator/BTHSControl). It's a bit quirky sometimes, but mostly it works.
