### ISSUE TITLE
Refresh feed

### ISSUE THREAD

**Issue by kokarn** [gillesdemey/Cumulus#5]
Still loving this player, it's so awesome. (Sorry for all the issues reported, just trying to help out ^^)

Today i noticed that the feed in Cumulus doesn't seem to update.

In Cumulus
![My current feed in Cumulus](https://i.imgur.com/Qvg217L.png)
On soundcloud.com
![My current feed on the site](https://i.imgur.com/Rcz6W3d.png)

After i restart Cumulus, i get the correct feed.
![Feed in Cumulus after restart](https://i.imgur.com/koA19wQ.png)

**Comment by MichielDeMey** [comment]
Hi, thanks for the bug report!
This is a known issue, we're going to have to implement a refresh option to reload your list.

If you have any suggestions, feel free to post them here.
A button would be the easiest to implement but we're trying to keep the app user friendly and uncluttered.

**Comment by Bitbored** [comment]
There seems to be a `future_href ` property in the activities result for this purpose. Maybe we could check it as soon as the app is activated (the tray icon is clicked)? This way we only have to do this request when we know the user might actually want it. I'm personally not a big fan of polling the `future_href` in the background... When the tracks are playing they go "back in time" anyway.

When a request to the `future_href ` resource returns a result we should probably display some loading animation on top of the list, and add the new tracks to the top of the list when they have been loaded.

**Comment by kokarn** [comment]
Yeah, i agree with @Bitbored. It seems unneeded to do it unless the user activates the app. 

The only case i might think up is that if they press "previous track" enough to go back to the first track and then press "previous track" again.

**Comment by gillesdemey** [comment]
I'm proposing to check for new tracks when 
* a user focuses the app, regardless of what tab is currently active
* a user switches to the Feed tab

For every check we should have an arbitrary timeout to determine wether or not we've recently checked for new content to avoid making too many request. Any suggestions are welcome.

We'll have to make sure to also prepend the new tracks to the playlist, so the `previousTrack` function works as intended.

I don't intend to check for new tracks when the user goes back to the top of the feed using media keys though, it's nice to have but most users will probably skip forward.

**Comment by kokarn** [comment]
Wow, this looks really good! Will try out and see if I can find some bugs with it ;)

On the timeout thing, i tried to find what you set but couldn't actually find it in any commits. I might be stupid tho, so sorry if that's the case. 
I think something like a minute would be good enough? 

PS: Would you mind adding the binary to the [releases tab](https://github.com/gillesdemey/Cumulus/releases)? Maybe something like [OBS studio](https://github.com/jp9000/obs-studio/releases) does?

**Comment by maertz** [comment]
That issue hasn't been fixed yet right? Still required a full restart to get the new update or is there some other way? Clicked the other tabs, closed / opened the menu bar but nothing happens :-1: although this thing is just what I was looking for a long time ... so :+1: and thanks for sharing!

**Comment by gillesdemey** [comment]
Hey @maertz this issue is still open.

I'll try to get some work in on Sunday and try to knock this out.

**Comment by kokarn** [comment]
Would be great! 
Only real issue I have with the client at the moment. No stress tho ;)
