### ISSUE TITLE
Option to disable notification sounds

### ISSUE THREAD

**Issue by rnarian** [gillesdemey/Cumulus#53]
Right now the app plays notification sounds on every track change, which is a bit annoying. At least to me, as I'm mistaking it for a chat notification. (Telegram uses the same notification sound.)

**Comment by gillesdemey** [comment]
This has been added in a recent version of Electron, I'll look into a way to disable the sound — in the interim you can disable notification sounds using System Preferences in OSX :)

**Comment by rnarian** [comment]
Ha! Didn't even think about that. :trollface: 

Thanks man!

**Comment by MichielDeMey** [comment]
Fixed in https://github.com/gillesdemey/Cumulus/pull/55! ;)
