### ISSUE TITLE
App has crashed after click on "Sign in with Google"

### ISSUE THREAD

**Issue by slydeveloper** [gillesdemey/Cumulus#63]
![cumulus](https://cloud.githubusercontent.com/assets/7541769/16207735/08dba9a6-372f-11e6-937e-14ffc9260558.png)
v0.7.1

**Comment by BobQuentok** [comment]
Same error
Cumulus 0.7.1
OS X 10.11.5 (15F34)

**Comment by MichielDeMey** [comment]
Duplicate of https://github.com/gillesdemey/Cumulus/issues/34.
Feel free to discuss/report the issues further over there.
