### ISSUE TITLE
Sound output source switching is ignored

### ISSUE THREAD

**Issue by virtualize** [gillesdemey/Cumulus#68]
Thanks for the app. Love it! But also found an unpleasant bug:
If a song is playing and I switch the output source (e.g. in osx sound preferences from internal to usb soundcard or cinema display) the switch is simply ignored. Have to quit cumulus, switch source, start cumulus. I'm usually switching a few times a day between headphones and speakers, so this is quite annoying.

**Comment by MichielDeMey** [comment]
I've seen the exact same issue on Spotify (macOS) as well, which leads me to believe the issue extends beyond Cumulus.

**Comment by virtualize** [comment]
I'm also using https://github.com/Soundnode/soundnode-app (also basically JS / Soundcloud API) and there switching sound sources works flawlessly. Maybe this could help as pointer.

**Comment by MichielDeMey** [comment]
They uses nw.js instead of electron, which is a different engine. We'll look into this, but the problem (and possible solution) is probably in the electron source.

**Comment by virtualize** [comment]
Ok. Thanks for taking the time.
