### ISSUE TITLE
Can't paste password when logging in

### ISSUE THREAD

**Issue by bradsimantel** [gillesdemey/Cumulus#8]
I can't paste a password into the login form, which makes using a password manager with Cumulus really difficult.

**Comment by gillesdemey** [comment]
I'll look into this

**Comment by bradsimantel** [comment]
Thanks!

**Comment by gillesdemey** [comment]
Unfortunately we're still figuring out why packaging the application has different behaviour on all platforms. I've reported the issue and it's being tracked here: https://github.com/atom/electron/issues/2402#issuecomment-127082576

I'm going to re-open this issue until we have it figured out.

**Comment by gillesdemey** [comment]
Hey @bradsimantel 

I've resolved the issue in the latest version. Could you re-download the application and let me know if it works?

There isn't a way to sign out yet through the user interface, but removing the stored access token will effectively sign you out.

Running `rm ~/Library/Application\ Support/Cumulus/config.json` will remove it so you can log in again.

**Comment by bradsimantel** [comment]
Logging back in, copy and paste now work on OS X 10.10.4! Thanks for being super responsive about this issue!
