### ISSUE TITLE
Skipping tracks

### ISSUE THREAD

**Issue by evanknight** [gillesdemey/Cumulus#93]
In version 10.0 it was skipping all tracks when I pressed play, and it's doing the same thing in 10.1 :( 

![screen shot 2017-04-21 at 2 51 05 pm](https://cloud.githubusercontent.com/assets/4306462/25295742/14cda814-26a2-11e7-955d-2a3f4bd00fe6.png)

**Comment by Hum4n01d** [comment]
This is because of https://github.com/gillesdemey/Cumulus/issues/89

**Comment by Hum4n01d** [comment]
@gillesdemey Please close this :)
