### ISSUE TITLE
Skips through every song

### ISSUE THREAD

**Issue by Petetheodddog** [gillesdemey/Cumulus#96]
When a song is clicked to be played, it doesn't play it just skips through every single song it can play/skip through. 

![may-17-2017 12-34-08](https://cloud.githubusercontent.com/assets/6750242/26150100/308c7584-3afd-11e7-85f8-1d6132b06e43.gif)

**Comment by gillesdemey** [comment]
This is a known issue. We are occasionally hitting the SoundCloud rate limits, we've reached out to SoundCloud to have them increased but have not heard back from them yet.

Please follow the progress at https://github.com/gillesdemey/Cumulus/issues/89
