### ISSUE TITLE
Unable to play tracks

### ISSUE THREAD

**Issue by lukacosicnz** [gillesdemey/Cumulus#99]
I just installed v0.10.1 as a clean install from the dmg, logged into my soundcloud account, and no song will play, they just skip. I tried logging out, quitting, didn't help.

Here's a screen recording of it:
[bug.mp4.zip](https://github.com/gillesdemey/Cumulus/files/1099485/bug.mp4.zip)

**Comment by MichielDeMey** [comment]
Sounds like a duplicate of https://github.com/gillesdemey/Cumulus/issues/89. Best to follow the progress in that ticket.
